#pragma once

#define IDR_UI_FONT_REGULAR 201
#define IDR_UI_FONT_SEMIBOLD 202
#define IDR_UI_FONT_BOLD 203
#define IDR_UI_FONT_LICENSE 204
#define IDR_GENIE_HOOK 205

// Back-compat aliases.
#define IDR_JETBRAINS_MONO_REGULAR IDR_UI_FONT_REGULAR
#define IDR_JETBRAINS_MONO_BOLD IDR_UI_FONT_SEMIBOLD
#define IDR_JETBRAINS_MONO_LICENSE IDR_UI_FONT_LICENSE
